# 🎵 Spotify Listening History Analysis

## Comparative Analysis of Two Spotify Users (2020–2026)

**Tools Used**
- Python
- Pandas
- NumPy
- Plotly
- Google Colab

**Dataset**
- Spotify Extended Streaming History
- 224,427 listening records
- 2 users
- 2020–2026

## 1. Import Libraries

In [ ]:
# Veri analizi
import pandas as pd
import numpy as np

# Görselleştirme
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

# Dosya işlemleri
import glob
import os

# Tarih işlemleri
from datetime import datetime

print("✅ Kütüphaneler başarıyla yüklendi.")

✅ Kütüphaneler başarıyla yüklendi.

## 2. Extract ZIP Files

In [ ]:
import zipfile
import os

# Çıkarma klasörlerini oluştur
os.makedirs("data/ozlem", exist_ok=True)
os.makedirs("data/eren", exist_ok=True)

# ZIP dosyalarını çıkar
with zipfile.ZipFile("my_spotify_data_Ozlem.zip", "r") as zip_ref:
    zip_ref.extractall("data/ozlem")

with zipfile.ZipFile("my_spotify_data_Eren.zip", "r") as zip_ref:
    zip_ref.extractall("data/eren")

print("✅ ZIP dosyaları başarıyla çıkarıldı.")

✅ ZIP dosyaları başarıyla çıkarıldı.

## 3. Load Data

In [ ]:
import os

for root, dirs, files in os.walk("data"):
    level = root.replace("data", "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")
    for file in files:
        print(f"{indent}    {file}")

data/
    eren/
        Spotify Extended Streaming History/
            Streaming_History_Audio_2026_1.json
            Streaming_History_Video_2026.json
            ReadMeFirst_ExtendedStreamingHistory.pdf
            Streaming_History_Audio_2024.json
            Streaming_History_Audio_2025.json
            Streaming_History_Audio_2024_1.json
            Streaming_History_Video_2024.json
            Streaming_History_Audio_2026.json
            Streaming_History_Video_2025.json
    ozlem/
        Spotify Extended Streaming History/
            Streaming_History_Audio_2024_4.json
            Streaming_History_Audio_2026_1.json
            Streaming_History_Audio_2025_1.json
            Streaming_History_Video_2026.json
            ReadMeFirst_ExtendedStreamingHistory.pdf
            Streaming_History_Audio_2021.json
            Streaming_History_Audio_2024.json
            Streaming_History_Audio_2023_1.json
            Streaming_History_Audio_2024_2.json
            Streaming_History_Audio_2025_2.json
            Streaming_History_Audio_2025.json
            Streaming_History_Audio_2020.json
            Streaming_History_Audio_2024_1.json
            Streaming_History_Video_2024.json
            Streaming_History_Audio_2022.json
            Streaming_History_Audio_2023.json
            Streaming_History_Audio_2026.json
            Streaming_History_Video_2025.json
            Streaming_History_Audio_2024_3.json
            Streaming_History_Audio_2025_3.json

In [ ]:
from pathlib import Path

def load_spotify_data(user_folder, user_name):
    folder = Path(user_folder) / "Spotify Extended Streaming History"

    audio_files = sorted(folder.glob("Streaming_History_Audio*.json"))
    video_files = sorted(folder.glob("Streaming_History_Video*.json"))

    audio_list = []
    video_list = []

    for file in audio_files:
        df = pd.read_json(file)
        df["user"] = user_name
        df["content_type"] = "Audio"
        audio_list.append(df)

    for file in video_files:
        df = pd.read_json(file)
        df["user"] = user_name
        df["content_type"] = "Video"
        video_list.append(df)

    audio_df = pd.concat(audio_list, ignore_index=True) if audio_list else pd.DataFrame()
    video_df = pd.concat(video_list, ignore_index=True) if video_list else pd.DataFrame()

    return audio_df, video_df

In [ ]:
ozlem_audio, ozlem_video = load_spotify_data("data/ozlem", "Özlem")
eren_audio, eren_video = load_spotify_data("data/eren", "Eren")

print("Özlem Audio :", ozlem_audio.shape)
print("Özlem Video :", ozlem_video.shape)
print("Eren Audio  :", eren_audio.shape)
print("Eren Video  :", eren_video.shape)

Özlem Audio : (170909, 25)
Özlem Video : (264, 25)
Eren Audio  : (53518, 25)
Eren Video  : (138, 25)

## 4. Merge Data

In [ ]:
# Dört veri setini tek tabloda birleştir

audio_df = pd.concat([ozlem_audio, eren_audio], ignore_index=True)
video_df = pd.concat([ozlem_video, eren_video], ignore_index=True)

print("Audio:", audio_df.shape)
print("Video:", video_df.shape)

Audio: (224427, 25)
Video: (402, 25)

In [ ]:
audio_df.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,user,content_type
0,2020-08-18T10:24:20Z,"Android OS 7.0 API 24 (samsung, SM-G935F)",7482,TR,78.165.171.160,Beni Boş Yere Yorma,Gripin,nasılım biliyor musun?,spotify:track:3Bg5dIiR8q1Bbw2I1qYmIn,NaN,...,NaN,clickrow,endplay,False,False,False,NaN,False,Özlem,Audio
1,2020-08-18T10:27:26Z,"Android OS 7.0 API 24 (samsung, SM-G935F)",186216,TR,78.165.171.160,Ebruli,Gripin,Ezginin Günlüğü 40 Yıllık Şarkılar,spotify:track:6vLRCLXfuhQ67n8sZoaQuw,NaN,...,NaN,clickrow,trackdone,False,False,False,NaN,False,Özlem,Audio
2,2020-08-18T10:28:58Z,"Android OS 7.0 API 24 (samsung, SM-G935F)",90791,TR,78.165.171.160,Gemiler,Teoman,O,spotify:track:6RxF2qmsTBsXFgK0lx8WEj,NaN,...,NaN,trackdone,fwdbtn,False,False,False,NaN,False,Özlem,Audio
3,2020-08-18T10:29:00Z,"Android OS 7.0 API 24 (samsung, SM-G935F)",2406,TR,78.165.171.160,Mor Yazma,Umut Kaya,Umut Kaya,spotify:track:2OcUkq1zSIkoT1QAb2FmCr,NaN,...,NaN,fwdbtn,fwdbtn,False,False,False,NaN,False,Özlem,Audio
4,2020-08-18T10:29:02Z,"Android OS 7.0 API 24 (samsung, SM-G935F)",1507,TR,78.165.171.160,Elleri Ellerime,Duman,Duman 2,spotify:track:0o16NrUwcH3U0fEEPD79VB,NaN,...,NaN,fwdbtn,fwdbtn,False,False,False,NaN,False,Özlem,Audio

## 5. Data Understanding

In [ ]:
audio_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224427 entries, 0 to 224426
Data columns (total 25 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   ts                                 224427 non-null  object
 1   platform                           224427 non-null  object
 2   ms_played                          224427 non-null  int64
 3   conn_country                       224427 non-null  object
 4   ip_addr                            224427 non-null  object
 5   master_metadata_track_name         223099 non-null  object
 6   master_metadata_album_artist_name  223099 non-null  object
 7   master_metadata_album_album_name   223099 non-null  object
 8   spotify_track_uri                  223099 non-null  object
 9   episode_name                       1328 non-null    object
 10  episode_show_name                  1328 non-null    object
 11  spotify_episode_uri                1328 non-null    object
 12  audiobook_title                    0 non-null       float64
 13  audiobook_uri                      0 non-null       float64
 14  audiobook_chapter_uri              0 non-null       float64
 15  audiobook_chapter_title            0 non-null       float64
 16  reason_start                       224427 non-null  object
 17  reason_end                         224427 non-null  object
 18  shuffle                            224427 non-null  bool
 19  skipped                            224427 non-null  bool
 20  offline                            224427 non-null  bool
 21  offline_timestamp                  219925 non-null  float64
 22  incognito_mode                     224427 non-null  bool
 23  user                               224427 non-null  object
 24  content_type                       224427 non-null  object
dtypes: bool(4), float64(5), int64(1), object(15)
memory usage: 36.8+ MB

In [ ]:
audio_df.describe(include="all")

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,user,content_type
count,224427,224427,2.244270e+05,224427,224427,223099,223099,223099,223099,1328,...,0.0,224427,224427,224427,224427,224427,2.199250e+05,224427,224427,224427
unique,216560,8,NaN,8,6247,11780,3764,9001,14253,640,...,NaN,12,10,2,2,2,NaN,2,2,1
top,2020-08-28T15:22:16Z,android,NaN,TR,78.167.153.181,Still With You,BTS,GOLDEN,spotify:track:0eFMbKCRw8KByXyWBw8WO7,No.1 x Ceza x Stabil x Hidra - Anlamazdın,...,NaN,fwdbtn,fwdbtn,False,True,False,NaN,False,Özlem,Audio
freq,7,107018,NaN,223577,3489,862,10580,4004,861,50,...,NaN,96168,93547,113488,148195,221596,NaN,224423,170909,224427
mean,NaN,NaN,8.665449e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.796426e+09,NaN,NaN,NaN
std,NaN,NaN,1.104769e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,9.980209e+09,NaN,NaN,NaN
min,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.665768e+09,NaN,NaN,NaN
25%,NaN,NaN,1.237000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.717149e+09,NaN,NaN,NaN
50%,NaN,NaN,1.085700e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.735883e+09,NaN,NaN,NaN
75%,NaN,NaN,1.854800e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.755974e+09,NaN,NaN,NaN
max,NaN,NaN,2.032393e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.664972e+12,NaN,NaN,NaN

In [ ]:
audio_df.isnull().sum().sort_values(ascending=False)

audiobook_title                      224427
audiobook_uri                        224427
audiobook_chapter_uri                224427
audiobook_chapter_title              224427
spotify_episode_uri                  223099
episode_show_name                    223099
episode_name                         223099
offline_timestamp                      4502
spotify_track_uri                      1328
master_metadata_album_album_name       1328
master_metadata_track_name             1328
master_metadata_album_artist_name      1328
platform                                  0
ts                                        0
ms_played                                 0
conn_country                              0
ip_addr                                   0
reason_start                              0
reason_end                                0
skipped                                   0
shuffle                                   0
offline                                   0
incognito_mode                            0
user                                      0
content_type                              0
dtype: int64

In [ ]:
spotify = audio_df.copy()

print(spotify.shape)

(224427, 25)

## 6. Feature Engineering

In [ ]:
spotify["ts"] = pd.to_datetime(spotify["ts"])

spotify["year"] = spotify["ts"].dt.year
spotify["month"] = spotify["ts"].dt.month
spotify["day"] = spotify["ts"].dt.day
spotify["hour"] = spotify["ts"].dt.hour
spotify["weekday"] = spotify["ts"].dt.day_name()

spotify.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,offline,offline_timestamp,incognito_mode,user,content_type,year,month,day,hour,weekday
0,2020-08-18 10:24:20+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",7482,TR,78.165.171.160,Beni Boş Yere Yorma,Gripin,nasılım biliyor musun?,spotify:track:3Bg5dIiR8q1Bbw2I1qYmIn,NaN,...,False,NaN,False,Özlem,Audio,2020,8,18,10,Tuesday
1,2020-08-18 10:27:26+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",186216,TR,78.165.171.160,Ebruli,Gripin,Ezginin Günlüğü 40 Yıllık Şarkılar,spotify:track:6vLRCLXfuhQ67n8sZoaQuw,NaN,...,False,NaN,False,Özlem,Audio,2020,8,18,10,Tuesday
2,2020-08-18 10:28:58+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",90791,TR,78.165.171.160,Gemiler,Teoman,O,spotify:track:6RxF2qmsTBsXFgK0lx8WEj,NaN,...,False,NaN,False,Özlem,Audio,2020,8,18,10,Tuesday
3,2020-08-18 10:29:00+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",2406,TR,78.165.171.160,Mor Yazma,Umut Kaya,Umut Kaya,spotify:track:2OcUkq1zSIkoT1QAb2FmCr,NaN,...,False,NaN,False,Özlem,Audio,2020,8,18,10,Tuesday
4,2020-08-18 10:29:02+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",1507,TR,78.165.171.160,Elleri Ellerime,Duman,Duman 2,spotify:track:0o16NrUwcH3U0fEEPD79VB,NaN,...,False,NaN,False,Özlem,Audio,2020,8,18,10,Tuesday

In [ ]:
spotify[["ts","year","month","day","hour","weekday"]].head()

                         ts  year  month  day  hour  weekday
0 2020-08-18 10:24:20+00:00  2020      8   18    10  Tuesday
1 2020-08-18 10:27:26+00:00  2020      8   18    10  Tuesday
2 2020-08-18 10:28:58+00:00  2020      8   18    10  Tuesday
3 2020-08-18 10:29:00+00:00  2020      8   18    10  Tuesday
4 2020-08-18 10:29:02+00:00  2020      8   18    10  Tuesday

In [ ]:
# Additional time-based features

spotify["date"] = spotify["ts"].dt.date
spotify["week"] = spotify["ts"].dt.isocalendar().week
spotify["day_name"] = spotify["ts"].dt.day_name()
spotify["month_name"] = spotify["ts"].dt.month_name()

spotify.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,content_type,year,month,day,hour,weekday,date,week,day_name,month_name
0,2020-08-18 10:24:20+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",7482,TR,78.165.171.160,Beni Boş Yere Yorma,Gripin,nasılım biliyor musun?,spotify:track:3Bg5dIiR8q1Bbw2I1qYmIn,NaN,...,Audio,2020,8,18,10,Tuesday,2020-08-18,34,Tuesday,August
1,2020-08-18 10:27:26+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",186216,TR,78.165.171.160,Ebruli,Gripin,Ezginin Günlüğü 40 Yıllık Şarkılar,spotify:track:6vLRCLXfuhQ67n8sZoaQuw,NaN,...,Audio,2020,8,18,10,Tuesday,2020-08-18,34,Tuesday,August
2,2020-08-18 10:28:58+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",90791,TR,78.165.171.160,Gemiler,Teoman,O,spotify:track:6RxF2qmsTBsXFgK0lx8WEj,NaN,...,Audio,2020,8,18,10,Tuesday,2020-08-18,34,Tuesday,August
3,2020-08-18 10:29:00+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",2406,TR,78.165.171.160,Mor Yazma,Umut Kaya,Umut Kaya,spotify:track:2OcUkq1zSIkoT1QAb2FmCr,NaN,...,Audio,2020,8,18,10,Tuesday,2020-08-18,34,Tuesday,August
4,2020-08-18 10:29:02+00:00,"Android OS 7.0 API 24 (samsung, SM-G935F)",1507,TR,78.165.171.160,Elleri Ellerime,Duman,Duman 2,spotify:track:0o16NrUwcH3U0fEEPD79VB,NaN,...,Audio,2020,8,18,10,Tuesday,2020-08-18,34,Tuesday,August

In [ ]:
print(f"Total records: {len(spotify):,}")
print(f"Date range: {spotify['ts'].min()} → {spotify['ts'].max()}")
print(f"Number of users: {spotify['user'].nunique()}")
print(f"Users: {spotify['user'].unique()}")
print(f"Number of artists: {spotify['master_metadata_album_artist_name'].nunique()}")
print(f"Number of tracks: {spotify['master_metadata_track_name'].nunique()}")

Total records: 224,427
Date range: 2020-08-18 10:24:20+00:00 → 2026-07-23 19:45:57+00:00
Number of users: 2
Users: ['Özlem' 'Eren']
Number of artists: 3764
Number of tracks: 11780

# 7. Exploratory Data Analysis

## 7.1 Top Artists

In [ ]:
artist_comparison = (
    spotify
    .dropna(subset=["master_metadata_album_artist_name"])
    .pivot_table(
        index="master_metadata_album_artist_name",
        columns="user",
        values="ms_played",
        aggfunc="count",
        fill_value=0
    )
)

artist_comparison["Total"] = artist_comparison.sum(axis=1)

artist_comparison = artist_comparison.sort_values(
    "Total",
    ascending=False
)

artist_comparison.head(20)

user                               Eren  Özlem  Total
master_metadata_album_artist_name
BTS                                  11  10569  10580
Jung Kook                            10   6108   6118
Gülşen                               58   4908   4966
Yalın                               460   3836   4296
Chase Atlantic                        0   4167   4167
Engin Nursani                      3012      0   3012
Ariana Grande                         0   2955   2955
Sancak                               21   2568   2589
Sezen Aksu                          264   2060   2324
Semicenk                           1349    971   2320
Ferdi Tayfur                       2268     24   2292
BLOK3                              1145    942   2087
Murat Dalkılıç                       66   1994   2060
The Weeknd                            3   1988   1991
Maroon 5                              1   1951   1952
Dedublüman                          245   1400   1645
Kıvırcık Ali Özütemiz              1637      3   1640
emre aydın                           43   1595   1638
Taylor Swift                          0   1613   1613
Yusuf Güney                          12   1596   1608

In [ ]:
artist_comparison["Dominant Listener"] = np.where(
    artist_comparison["Özlem"] > artist_comparison["Eren"],
    "Özlem",
    np.where(
        artist_comparison["Eren"] > artist_comparison["Özlem"],
        "Eren",
        "Equal"
    )
)

artist_comparison.head(20)

user                               Eren  Özlem  Total Dominant Listener
master_metadata_album_artist_name
BTS                                  11  10569  10580             Özlem
Jung Kook                            10   6108   6118             Özlem
Gülşen                               58   4908   4966             Özlem
Yalın                               460   3836   4296             Özlem
Chase Atlantic                        0   4167   4167             Özlem
Engin Nursani                      3012      0   3012              Eren
Ariana Grande                         0   2955   2955             Özlem
Sancak                               21   2568   2589             Özlem
Sezen Aksu                          264   2060   2324             Özlem
Semicenk                           1349    971   2320              Eren
Ferdi Tayfur                       2268     24   2292              Eren
BLOK3                              1145    942   2087              Eren
Murat Dalkılıç                       66   1994   2060             Özlem
The Weeknd                            3   1988   1991             Özlem
Maroon 5                              1   1951   1952             Özlem
Dedublüman                          245   1400   1645             Özlem
Kıvırcık Ali Özütemiz              1637      3   1640              Eren
emre aydın                           43   1595   1638             Özlem
Taylor Swift                          0   1613   1613             Özlem
Yusuf Güney                          12   1596   1608             Özlem

In [ ]:
top_tracks = (
    spotify
    .dropna(subset=["master_metadata_track_name"])
    .groupby(
        [
            "master_metadata_track_name",
            "master_metadata_album_artist_name"
        ]
    )
    .size()
    .reset_index(name="play_count")
    .sort_values("play_count", ascending=False)
    .head(20)
)

top_tracks

,master_metadata_track_name,master_metadata_album_artist_name,play_count
9831,Still With You,Jung Kook,861
87,3D (feat. Jack Harlow),Jung Kook,599
2738,Closer to You (feat. Major Lazer),Jung Kook,578
7974,"One Of The Girls (with JENNIE, Lily Rose Depp)",The Weeknd,550
12071,double take,Dhruv,548
2104,Bite Me,ENHYPEN,535
842,Attention,Charlie Puth,521
8560,Run BTS,BTS,519
5701,Into You,Ariana Grande,516
9375,Seven (feat. Latto) (Explicit Ver.),Jung Kook,500
9467,Señorita,Shawn Mendes,487
2218,Boy With Luv (feat. Halsey),BTS,485
3941,FAKE LOVE,BTS,485
2438,Butter,BTS,484
10946,Walls Could Talk,Halsey,471
6865,Love Me Again,V,462
11065,Without Me,Halsey,459
10289,That That (prod.&feat. SUGA of BTS),PSY,455
11616,Yes or No,Jung Kook,453
4915,HEAVEN AND BACK,Chase Atlantic,449

In [ ]:
fig = px.bar(
    top_tracks,
    x="play_count",
    y="master_metadata_track_name",
    color="master_metadata_album_artist_name",
    orientation="h",
    title="Top 20 Most Played Tracks",
    labels={
        "master_metadata_track_name": "Track",
        "master_metadata_album_artist_name": "Artist",
        "play_count": "Play Count"
    }
)

fig.update_layout(
    yaxis={"categoryorder": "total ascending"},
    legend_title="Artist"
)

fig.show()

## 8.3 Listening Activity by Hour

In [ ]:
hourly_activity = (
    spotify
    .groupby("hour")
    .size()
    .reset_index(name="play_count")
)

hourly_activity

    hour  play_count
0      0        2878
1      1        1889
2      2        1384
3      3        2860
4      4        3751
5      5        4895
6      6        5541
7      7        7452
8      8       10564
9      9       11866
10    10       14874
11    11       15232
12    12       14533
13    13       14907
14    14       14963
15    15       12657
16    16       12121
17    17       10893
18    18       13983
19    19       16914
20    20       13116
21    21        8730
22    22        5429
23    23        2995

In [ ]:
fig = px.line(
    hourly_activity,
    x="hour",
    y="play_count",
    markers=True,
    title="Listening Activity by Hour",
    labels={
        "hour": "Hour of Day",
        "play_count": "Play Count"
    }
)

fig.update_xaxes(dtick=1)

fig.show()

## 8.4 Listening Activity by Weekday

In [ ]:
weekday_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

weekday_activity = (
    spotify
    .groupby("weekday")
    .size()
    .reindex(weekday_order)
    .reset_index(name="play_count")
)

weekday_activity

     weekday  play_count
0     Monday       31959
1    Tuesday       32487
2  Wednesday       31472
3   Thursday       31883
4     Friday       33661
5   Saturday       33206
6     Sunday       29759

In [ ]:
fig = px.bar(
    weekday_activity,
    x="weekday",
    y="play_count",
    title="Listening Activity by Weekday",
    labels={
        "weekday": "Weekday",
        "play_count": "Play Count"
    }
)

fig.show()

## 8.5 Listening Activity by Month

In [ ]:
month_order = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

monthly_activity = (
    spotify
    .groupby("month_name")
    .size()
    .reindex(month_order)
    .reset_index(name="play_count")
)

monthly_activity

   month_name  play_count
0     January       18114
1    February       19615
2       March       17624
3       April       19424
4         May       23203
5        June       19376
6        July       24004
7      August       19542
8   September       17699
9     October       15060
10   November       15021
11   December       15745

In [ ]:
fig = px.bar(
    monthly_activity,
    x="month_name",
    y="play_count",
    title="Listening Activity by Month",
    labels={
        "month_name": "Month",
        "play_count": "Play Count"
    }
)

fig.show()

## 8.6 Listening Activity by Year

In [ ]:
yearly_activity = (
    spotify
    .groupby("year")
    .size()
    .reset_index(name="play_count")
)

yearly_activity

   year  play_count
0  2020        1672
1  2021          72
2  2022        8712
3  2023       16279
4  2024       87321
5  2025       73396
6  2026       36975

In [ ]:
fig = px.line(
    yearly_activity,
    x="year",
    y="play_count",
    markers=True,
    title="Listening Activity by Year",
    labels={
        "year": "Year",
        "play_count": "Play Count"
    }
)

fig.show()

## 8.7 Platform Analysis

In [ ]:
platform_activity = (
    spotify
    .groupby("platform")
    .size()
    .reset_index(name="play_count")
    .sort_values("play_count", ascending=False)
)

platform_activity

                                            platform  play_count
5                                            android      107018
6                                                ios       95205
7                                            windows       17694
1          Android OS 7.0 API 24 (samsung, SM-G935F)        3482
3                 Windows 10 (10.0.22000; x64; AppX)         852
4                 Windows 10 (10.0.22621; x64; AppX)          98
0        Android OS 11 API 30 (Xiaomi, Redmi Note 8)          72
2  Android OS 8.0.0 API 26 (General Mobile, GM 5 ...           6

In [ ]:
fig = px.bar(
    platform_activity,
    x="play_count",
    y="platform",
    orientation="h",
    title="Listening Activity by Platform",
    labels={
        "platform": "Platform",
        "play_count": "Play Count"
    }
)

fig.update_layout(yaxis={"categoryorder": "total ascending"})

fig.show()

## 8.8 Shuffle Analysis

In [ ]:
shuffle_activity = (
    spotify["shuffle"]
    .value_counts()
    .rename_axis("shuffle")
    .reset_index(name="count")
)

shuffle_activity

   shuffle   count
0    False  113488
1     True  110939

In [ ]:
fig = px.pie(
    shuffle_activity,
    values="count",
    names="shuffle",
    title="Shuffle Usage"
)

fig.show()

## 8.9 Skip Analysis

In [ ]:
skip_activity = (
    spotify["skipped"]
    .value_counts()
    .rename_axis("skipped")
    .reset_index(name="count")
)

skip_activity

   skipped   count
0     True  148195
1    False   76232

In [ ]:
fig = px.pie(
    skip_activity,
    values="count",
    names="skipped",
    title="Skipped vs Completed Plays"
)

fig.show()

## 8.10 Listening Time Analysis

In [ ]:
spotify["hours_played"] = spotify["ms_played"] / (1000 * 60 * 60)

listening_time = (
    spotify
    .groupby("user")["hours_played"]
    .sum()
    .reset_index()
)

listening_time

    user  hours_played
0   Eren   1354.964252
1  Özlem   4047.148917

In [ ]:
fig = px.bar(
    listening_time,
    x="user",
    y="hours_played",
    title="Total Listening Time by User",
    labels={
        "user": "User",
        "hours_played": "Hours"
    }
)

fig.show()

## 9. User Comparison

9.1 General Comparison

In [ ]:
comparison = (
    spotify
    .groupby("user")
    .agg(
        Total_Plays=("master_metadata_track_name", "count"),
        Total_Artists=("master_metadata_album_artist_name", "nunique"),
        Total_Tracks=("master_metadata_track_name", "nunique"),
        Listening_Hours=("hours_played", "sum")
    )
    .round(2)
)

comparison

       Total_Plays  Total_Artists  Total_Tracks  Listening_Hours
user
Eren         53036           1791          5799          1354.96
Özlem       170063           2661          7937          4047.15

In [ ]:
comparison_plot = comparison.reset_index()

fig = px.bar(
    comparison_plot,
    x="user",
    y="Listening_Hours",
    text="Listening_Hours",
    title="Total Listening Hours by User",
    labels={
        "user": "User",
        "Listening_Hours": "Hours"
    }
)

fig.show()

9.2 Top 10 Artists for Each User

In [ ]:
top_user_artists = (
    spotify
    .dropna(subset=["master_metadata_album_artist_name"])
    .groupby(["user", "master_metadata_album_artist_name"])
    .size()
    .reset_index(name="play_count")
)

top_user_artists

       user master_metadata_album_artist_name  play_count
0      Eren                             ''Xav          27
1      Eren                           17F4tih           3
2      Eren                          2 Chainz           1
3      Eren                              2Pac           2
4      Eren                           3 Hürel           1
...     ...                               ...         ...
4447  Özlem                             Şimal           1
4448  Özlem                             Нервы           2
4449  Özlem                             фрози          18
4450  Özlem                             蕊蕊蕊蕊!           1
4451  Özlem               정중한 Chung Joong Han           1

[4452 rows x 3 columns]

In [ ]:
fig = px.bar(
    top_user_artists.sort_values("play_count", ascending=False).groupby("user").head(10),
    x="play_count",
    y="master_metadata_album_artist_name",
    color="user",
    facet_col="user",
    orientation="h",
    title="Top 10 Artists for Each User"
)

fig.update_layout(height=600)

fig.show()

9.3 Top 10 Tracks for Each User

In [ ]:
top_user_tracks = (
    spotify
    .dropna(subset=["master_metadata_track_name"])
    .groupby(
        [
            "user",
            "master_metadata_track_name"
        ]
    )
    .size()
    .reset_index(name="play_count")
)

top_user_tracks

        user                         master_metadata_track_name  play_count
0       Eren                                    #PHONKFREESTYLE           1
1       Eren                                         #işbirliği           1
2       Eren  (When You Gonna) Give It Up to Me - Radio Version           1
3       Eren                                    ...sakın unutma           1
4       Eren                                              1 YIL           9
...      ...                                                ...         ...
13731  Özlem                                            잠시 안녕처럼           1
13732  Özlem                                             좋다고 말해           1
13733  Özlem                                      항상 (HANGSANG)           3
13734  Özlem                                          해야 (HEYA)           1
13735  Özlem                                 헤픈엔딩 Happen Ending           1

[13736 rows x 3 columns]

In [ ]:
fig = px.bar(
    top_user_tracks.sort_values("play_count", ascending=False).groupby("user").head(10),
    x="play_count",
    y="master_metadata_track_name",
    color="user",
    facet_col="user",
    orientation="h",
    title="Top 10 Tracks for Each User"
)

fig.update_layout(height=600)

fig.show()

9.4 Listening Hours by Hour (Comparison)

In [ ]:
hour_user = (
    spotify
    .groupby(["hour", "user"])
    .size()
    .reset_index(name="play_count")
)

hour_user.head()

   hour   user  play_count
0     0   Eren        1847
1     0  Özlem        1031
2     1   Eren        1246
3     1  Özlem         643
4     2   Eren         644

In [ ]:
fig = px.line(
    hour_user,
    x="hour",
    y="play_count",
    color="user",
    markers=True,
    title="Listening Activity by Hour (User Comparison)",
    labels={
        "hour": "Hour",
        "play_count": "Play Count"
    }
)

fig.update_xaxes(dtick=1)

fig.show()

## 10. Music Taste Similarity

10.1 Common Artists

In [ ]:
ozlem_artists = set(
    spotify.loc[
        spotify["user"] == "Özlem",
        "master_metadata_album_artist_name"
    ].dropna()
)

eren_artists = set(
    spotify.loc[
        spotify["user"] == "Eren",
        "master_metadata_album_artist_name"
    ].dropna()
)

common_artists = ozlem_artists & eren_artists

print("Common artists:", len(common_artists))

Common artists: 688

10.2 Unique Artists

In [ ]:
only_ozlem = ozlem_artists - eren_artists
only_eren = eren_artists - ozlem_artists

print("Only Özlem:", len(only_ozlem))
print("Only Eren :", len(only_eren))

Only Özlem: 1973
Only Eren : 1103

10.3 Music Taste Similarity Score

Similarity= Union/Common
	​

In [ ]:
similarity = (
    len(common_artists)
    /
    len(ozlem_artists | eren_artists)
)

print(f"Music Taste Similarity: {similarity:.2%}")

Music Taste Similarity: 18.28%

10.4 Top Common Artists

In [ ]:
common_artist_stats = (
    spotify[
        spotify["master_metadata_album_artist_name"].isin(common_artists)
    ]
    .groupby("master_metadata_album_artist_name")
    .size()
    .reset_index(name="play_count")
    .sort_values("play_count", ascending=False)
    .head(20)
)

common_artist_stats

    master_metadata_album_artist_name  play_count
75                                BTS       10580
306                         Jung Kook        6118
266                            Gülşen        4966
602                             Yalın        4296
502                            Sancak        2589
524                        Sezen Aksu        2324
515                          Semicenk        2320
226                      Ferdi Tayfur        2292
74                              BLOK3        2087
405                    Murat Dalkılıç        2060
561                        The Weeknd        1991
379                          Maroon 5        1952
151                        Dedublüman        1645
346             Kıvırcık Ali Özütemiz        1640
635                        emre aydın        1638
612                       Yusuf Güney        1608
324                        Katy Perry        1506
665                             Özgün        1495
280                       Hande Yener        1494
538                Soner Sarıkabadayı        1426

In [ ]:
fig = px.bar(
    common_artist_stats,
    x="play_count",
    y="master_metadata_album_artist_name",
    orientation="h",
    title="Top 20 Common Artists",
    labels={
        "master_metadata_album_artist_name":"Artist",
        "play_count":"Play Count"
    }
)

fig.update_layout(
    yaxis={"categoryorder":"total ascending"}
)

fig.show()

10.5 Exclusive Artists

In [ ]:
only_ozlem_stats = (
    spotify[
        (spotify["user"] == "Özlem") &
        (spotify["master_metadata_album_artist_name"].isin(only_ozlem))
    ]
    .groupby("master_metadata_album_artist_name")
    .size()
    .reset_index(name="play_count")
    .sort_values("play_count", ascending=False)
    .head(20)
)

only_ozlem_stats

     master_metadata_album_artist_name  play_count
318                     Chase Atlantic        4167
125                      Ariana Grande        2955
1611                      Taylor Swift        1613
817                      Justin Bieber        1445
677                             Halsey        1410
1261                     One Direction        1309
730                      Isabel LaRosa        1082
185                          BLACKPINK        1016
123                     Arctic Monkeys         935
922                        LE SSERAFIM         889
984                         Little Mix         863
436                           Dua Lipa         846
1493                      Shawn Mendes         778
511                          Emre Kaya         736
830                            KATSEYE         663
571                      Fifth Harmony         640
291                     Camila Cabello         629
60                       Alec Benjamin         606
455                            ENHYPEN         578
257                         Bora Duran         570

In [ ]:
only_eren_stats = (
    spotify[
        (spotify["user"] == "Eren") &
        (spotify["master_metadata_album_artist_name"].isin(only_eren))
    ]
    .groupby("master_metadata_album_artist_name")
    .size()
    .reset_index(name="play_count")
    .sort_values("play_count", ascending=False)
    .head(20)
)

only_eren_stats

     master_metadata_album_artist_name  play_count
332                      Engin Nursani        3012
538                       Kıvırcık Ali         812
392                        Gamze Şeker         433
50                            Ali Çini         415
43                    Ali Haydar Güçlü         348
189                          Cash Flow         303
835                             Stabil         233
927                        Yasin Aydın         209
470              Hüseyin Korkankorkmaz         180
25                         Ahmet Aslan         169
652                     Mümin Sarıkaya         168
540                         Kızılırmak         163
813                    Seyfi Yerlikaya         160
944                       Yılmaz Çelik         148
700                     Orhan Gencebay         144
107                 Aşık Mahzuni Şerif         133
1049                       Çaçan Beats         130
46                         Ali Nursani         129
655                              NEYMO         115
44                           Ali Kınık         106

10.6 Top Exclusive Artists (Özlem)

In [ ]:
only_ozlem_stats = (
    spotify[
        (spotify["user"] == "Özlem") &
        (spotify["master_metadata_album_artist_name"].isin(only_ozlem))
    ]
    .groupby("master_metadata_album_artist_name")
    .size()
    .reset_index(name="play_count")
    .sort_values("play_count", ascending=False)
    .head(20)
)

only_ozlem_stats

     master_metadata_album_artist_name  play_count
318                     Chase Atlantic        4167
125                      Ariana Grande        2955
1611                      Taylor Swift        1613
817                      Justin Bieber        1445
677                             Halsey        1410
1261                     One Direction        1309
730                      Isabel LaRosa        1082
185                          BLACKPINK        1016
123                     Arctic Monkeys         935
922                        LE SSERAFIM         889
984                         Little Mix         863
436                           Dua Lipa         846
1493                      Shawn Mendes         778
511                          Emre Kaya         736
830                            KATSEYE         663
571                      Fifth Harmony         640
291                     Camila Cabello         629
60                       Alec Benjamin         606
455                            ENHYPEN         578
257                         Bora Duran         570

In [ ]:
fig = px.bar(
    only_ozlem_stats,
    x="play_count",
    y="master_metadata_album_artist_name",
    orientation="h",
    title="Top 20 Exclusive Artists - Özlem",
    labels={
        "master_metadata_album_artist_name": "Artist",
        "play_count": "Play Count"
    }
)

fig.update_layout(
    yaxis={"categoryorder": "total ascending"}
)

fig.show()

10.7 Top Exclusive Artists (Eren)

In [ ]:
only_eren_stats = (
    spotify[
        (spotify["user"] == "Eren") &
        (spotify["master_metadata_album_artist_name"].isin(only_eren))
    ]
    .groupby("master_metadata_album_artist_name")
    .size()
    .reset_index(name="play_count")
    .sort_values("play_count", ascending=False)
    .head(20)
)

only_eren_stats

     master_metadata_album_artist_name  play_count
332                      Engin Nursani        3012
538                       Kıvırcık Ali         812
392                        Gamze Şeker         433
50                            Ali Çini         415
43                    Ali Haydar Güçlü         348
189                          Cash Flow         303
835                             Stabil         233
927                        Yasin Aydın         209
470              Hüseyin Korkankorkmaz         180
25                         Ahmet Aslan         169
652                     Mümin Sarıkaya         168
540                         Kızılırmak         163
813                    Seyfi Yerlikaya         160
944                       Yılmaz Çelik         148
700                     Orhan Gencebay         144
107                 Aşık Mahzuni Şerif         133
1049                       Çaçan Beats         130
46                         Ali Nursani         129
655                              NEYMO         115
44                           Ali Kınık         106

In [ ]:
fig = px.bar(
    only_eren_stats,
    x="play_count",
    y="master_metadata_album_artist_name",
    orientation="h",
    title="Top 20 Exclusive Artists - Eren",
    labels={
        "master_metadata_album_artist_name": "Artist",
        "play_count": "Play Count"
    }
)

fig.update_layout(
    yaxis={"categoryorder": "total ascending"}
)

fig.show()


10.8 Similarity Summary

In [ ]:
similarity_summary = pd.DataFrame({
    "Metric": [
        "Common Artists",
        "Only Özlem",
        "Only Eren",
        "Similarity Score (%)"
    ],
    "Value": [
        len(common_artists),
        len(only_ozlem),
        len(only_eren),
        round(similarity * 100, 2)
    ]
})

similarity_summary

                 Metric    Value
0        Common Artists   688.00
1            Only Özlem  1973.00
2             Only Eren  1103.00
3  Similarity Score (%)    18.28

10.9 Similarity Chart

In [ ]:
fig = px.bar(
    similarity_summary.iloc[:3],
    x="Metric",
    y="Value",
    text="Value",
    title="Artist Library Comparison"
)

fig.show()

## 11. Music Evolution Over Time

11.4 Top Artist of Each Year

In [ ]:
top_artist_each_year = (
    spotify
    .dropna(subset=["master_metadata_album_artist_name"])
    .groupby(["year", "master_metadata_album_artist_name"])
    .size()
    .reset_index(name="play_count")
    .sort_values(["year", "play_count"], ascending=[True, False])
    .groupby("year")
    .head(1)
)

top_artist_each_year

      year master_metadata_album_artist_name  play_count
160   2020                             Yalın          82
194   2021                             Kargo           8
247   2022                     Ariana Grande         307
1003  2023                               BTS         814
2194  2024                               BTS        8891
3991  2025                            Gülşen        3055
5911  2026                            Gülşen        1413

In [ ]:
fig = px.bar(
    top_artist_each_year,
    x="year",
    y="play_count",
    color="master_metadata_album_artist_name",
    text="master_metadata_album_artist_name",
    title="Top Artist of Each Year",
    labels={
        "year": "Year",
        "play_count": "Play Count"
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    showlegend=False,
    xaxis_title="Year",
    yaxis_title="Play Count"
)

fig.show()

11.5 Artist Trend Over Time

In [ ]:
# İncelemek istediğin sanatçıyı yaz
selected_artist = "BTS"

artist_trend = (
    spotify[
        spotify["master_metadata_album_artist_name"] == selected_artist
    ]
    .groupby("year")
    .size()
    .reset_index(name="play_count")
)

artist_trend

   year  play_count
0  2020           1
1  2022           3
2  2023         814
3  2024        8891
4  2025         440
5  2026         431

In [ ]:
fig = px.line(
    artist_trend,
    x="year",
    y="play_count",
    markers=True,
    title=f"{selected_artist} Listening Trend Over Time",
    labels={
        "year": "Year",
        "play_count": "Play Count"
    }
)

fig.update_xaxes(dtick=1)

fig.show()

In [ ]:
selected_artist = "BTS"

artist_user_trend = (
    spotify[
        spotify["master_metadata_album_artist_name"] == selected_artist
    ]
    .groupby(["year", "user"])
    .size()
    .reset_index(name="play_count")
)

artist_user_trend

   year   user  play_count
0  2020  Özlem           1
1  2022  Özlem           3
2  2023  Özlem         814
3  2024   Eren           4
4  2024  Özlem        8887
5  2025   Eren           6
6  2025  Özlem         434
7  2026   Eren           1
8  2026  Özlem         430

In [ ]:
fig = px.line(
    artist_user_trend,
    x="year",
    y="play_count",
    color="user",
    markers=True,
    title=f"{selected_artist} Listening Trend by User",
    labels={
        "year": "Year",
        "play_count": "Play Count"
    }
)

fig.update_xaxes(dtick=1)

fig.show()

11.6 Fastest Growing Artists

In [ ]:
artist_year = (
    spotify
    .dropna(subset=["master_metadata_album_artist_name"])
    .groupby(["master_metadata_album_artist_name", "year"])
    .size()
    .reset_index(name="play_count")
)

artist_year.head()

  master_metadata_album_artist_name  year  play_count
0                           $h̟i͞b̢  2022           1
1                             ''Xav  2025          27
2                          (((())))  2022           1
3                          (((())))  2023           1
4                          (G)I-DLE  2023           4

In [ ]:
artist_year["growth"] = (
    artist_year
    .groupby("master_metadata_album_artist_name")["play_count"]
    .diff()
)

artist_year.head(15)

   master_metadata_album_artist_name  year  play_count  growth
0                            $h̟i͞b̢  2022           1     NaN
1                              ''Xav  2025          27     NaN
2                           (((())))  2022           1     NaN
3                           (((())))  2023           1     0.0
4                           (G)I-DLE  2023           4     NaN
5                           (G)I-DLE  2024           6     2.0
6                             *NSYNC  2024           1     NaN
7                             *NSYNC  2025           1     0.0
8                               10CM  2023           1     NaN
9                               10CM  2024         493   492.0
10                              10CM  2025          12  -481.0
11                              10CM  2026           1   -11.0
12                         13. Vagon  2023           4     NaN
13                           17F4tih  2025           3     NaN
14                        1da Banton  2025          11     NaN

In [ ]:
top_growth = (
    artist_year
    .dropna(subset=["growth"])
    .sort_values("growth", ascending=False)
    .head(20)
)

top_growth

     master_metadata_album_artist_name  year  play_count  growth
740                                BTS  2024        8891  8077.0
3103                         Jung Kook  2024        5095  4422.0
1329                    Chase Atlantic  2024        3380  3201.0
2597                            Gülşen  2025        3055  2702.0
440                      Ariana Grande  2024        1781  1490.0
3855                          Maroon 5  2024        1515  1477.0
2239                      Ferdi Tayfur  2024        1414  1409.0
3455             Kıvırcık Ali Özütemiz  2024        1373  1371.0
6142                             Yalın  2024        1372  1270.0
5760                        The Weeknd  2024        1402  1270.0
6237                       Yusuf Güney  2025        1314  1137.0
4505                     One Direction  2024        1185  1124.0
5117                            Sancak  2025        1291  1121.0
6776                             Özgün  2024        1071  1037.0
725                              BLOK3  2025        1161  1018.0
3109                     Justin Bieber  2024        1129   996.0
2698                            Halsey  2024        1101   968.0
5305                        Sezen Aksu  2025        1420   916.0
5572                              Sıla  2025        1025   871.0
5229                          Semicenk  2025        1465   851.0

In [ ]:
fig = px.bar(
    top_growth,
    x="growth",
    y="master_metadata_album_artist_name",
    orientation="h",
    color="year",
    text="growth",
    title="Top 20 Fastest Growing Artists",
    labels={
        "growth": "Increase in Play Count",
        "master_metadata_album_artist_name": "Artist"
    }
)

fig.update_layout(
    yaxis={"categoryorder": "total ascending"}
)

fig.show()

11.7 New Artists Discovered Each Year

In [ ]:
first_year = (
    spotify
    .dropna(subset=["master_metadata_album_artist_name"])
    .groupby("master_metadata_album_artist_name")["year"]
    .min()
    .reset_index(name="first_year")
)

new_artists = (
    first_year
    .groupby("first_year")
    .size()
    .reset_index(name="new_artists")
)

new_artists

   first_year  new_artists
0        2020          181
1        2021           11
2        2022          548
3        2023          754
4        2024          614
5        2025         1028
6        2026          628

In [ ]:
fig = px.bar(
    new_artists,
    x="first_year",
    y="new_artists",
    text="new_artists",
    title="New Artists Discovered Each Year",
    labels={
        "first_year": "Year",
        "new_artists": "New Artists"
    }
)

fig.show()

## 12. Listening Duration Analysis

12.1 Total Listening Hours by User

In [ ]:
user_hours = (
    spotify
    .groupby("user")["hours_played"]
    .sum()
    .reset_index()
)

user_hours

    user  hours_played
0   Eren   1354.964252
1  Özlem   4047.148917

In [ ]:
fig = px.bar(
    user_hours,
    x="user",
    y="hours_played",
    text="hours_played",
    color="user",
    title="Total Listening Hours by User",
    labels={
        "user": "User",
        "hours_played": "Hours Played"
    }
)

fig.show()

12.2 Average Song Duration

In [ ]:
avg_song = (
    spotify
    .groupby("user")["ms_played"]
    .mean()
    .reset_index()
)

avg_song["minutes"] = avg_song["ms_played"] / 60000

avg_song

    user     ms_played   minutes
0   Eren  91144.499215  1.519075
1  Özlem  85248.501261  1.420808

In [ ]:
fig = px.bar(
    avg_song,
    x="user",
    y="minutes",
    text=avg_song["minutes"].round(2),
    color="user",
    title="Average Listening Time per Track",
    labels={
        "minutes": "Minutes"
    }
)

fig.show()

## 13. Daily Listening Activity

13.1 Top 20 Listening Days

In [ ]:
daily_activity = (
    spotify
    .groupby("date")
    .agg(
        play_count=("master_metadata_track_name", "count"),
        hours_played=("hours_played", "sum")
    )
    .reset_index()
    .sort_values("hours_played", ascending=False)
    .head(20)
)

daily_activity

            date  play_count  hours_played
895   2025-04-03         323     11.428177
763   2024-11-22         376     11.124237
939   2025-05-17         433     11.069526
911   2025-04-19         260     11.057232
1314  2026-05-27         390     10.915781
987   2025-07-04         662     10.541191
773   2024-12-02         359     10.382186
839   2025-02-06         537     10.346754
955   2025-06-02         299     10.288351
823   2025-01-21         370     10.244138
990   2025-07-07         346     10.175739
965   2025-06-12         485     10.160388
992   2025-07-09         428      9.993613
952   2025-05-30         275      9.989509
766   2024-11-25         314      9.969292
1007  2025-07-24         449      9.959689
838   2025-02-05         554      9.790711
903   2025-04-11         220      9.721905
1055  2025-09-10         417      9.714492
840   2025-02-07         501      9.649801

In [ ]:
daily_activity["date"] = daily_activity["date"].astype(str)

fig = px.bar(
    daily_activity,
    x="date",
    y="hours_played",
    title="Top 20 Listening Days"
)

fig.show()

## 14. Day vs Night Listening

In [ ]:
spotify["period"] = np.where(
    spotify["hour"].between(6, 17),
    "Day",
    "Night"
)

period_stats = (
    spotify
    .groupby("period")
    .agg(
        play_count=("master_metadata_track_name", "count"),
        listening_hours=("hours_played", "sum")
    )
    .reset_index()
)

period_stats

  period  play_count  listening_hours
0    Day      145058      3531.344459
1  Night       78041      1870.768711

doughnut grafic

In [ ]:
fig = px.pie(
    period_stats,
    values="play_count",
    names="period",
    hole=0.45,
    title="Day vs Night Listening"
)

fig.show()

bar grafic

In [ ]:
fig = px.bar(
    period_stats,
    x="period",
    y="listening_hours",
    color="period",
    text=period_stats["listening_hours"].round(1),
    title="Listening Hours: Day vs Night",
    labels={
        "period": "Period",
        "listening_hours": "Hours"
    }
)

fig.show()

## 15 Top Albums Analysis

15.1 Top 20 Most Listened Albums

In [ ]:
top_albums = (
    spotify
    .dropna(subset=["master_metadata_album_album_name"])
    .groupby("master_metadata_album_album_name")
    .agg(
        play_count=("master_metadata_track_name", "count"),
        listening_hours=("hours_played", "sum")
    )
    .sort_values("play_count", ascending=False)
    .head(20)
)

top_albums

                                  play_count  listening_hours
master_metadata_album_album_name
GOLDEN                                  4004        63.501287
Adina Bir Çizik Çektim                  1522        54.260067
Love Yourself 結 'Answer'                1509        49.088951
Proof                                   1499        47.030681
Bangır Bangır                           1271        46.165408
V                                       1211        18.414560
Manifesto                               1049        22.495502
Dangerous Woman                         1022        18.999799
Bir Bakmışsın                           1011        27.418778
Chase Atlantic                           965        17.535175
Önsöz                                    919        34.927753
MAP OF THE SOUL : 7                      909        19.916642
AM                                       869        12.602838
Still With You                           862        47.279051
Onbir Bir İkibinonbir Veda               857        35.140709
Daha Derine                              849        16.358723
Beni Durdursan Mı ?                      847        26.085867
Love Yourself 轉 'Tear'                   828        32.227111
Gözyaşı                                  825        23.126333
BE                                       795        16.579212

In [ ]:
fig = px.bar(
    top_albums.reset_index(),
    x="play_count",
    y="master_metadata_album_album_name",
    orientation="h",
    color="listening_hours",
    text="play_count",
    title="Top 20 Most Listened Albums",
    labels={
        "master_metadata_album_album_name": "Album",
        "play_count": "Play Count",
        "listening_hours": "Listening Hours"
    }
)

fig.update_layout(
    yaxis={"categoryorder": "total ascending"}
)

fig.show()

15.2 Album Listening Hours

In [ ]:
album_hours = (
    spotify
    .dropna(subset=["master_metadata_album_album_name"])
    .groupby("master_metadata_album_album_name")["hours_played"]
    .sum()
    .sort_values(ascending=False)
    .head(20)
    .reset_index()
)

album_hours

   master_metadata_album_album_name  hours_played
0                            GOLDEN     63.501287
1            Adina Bir Çizik Çektim     54.260067
2          Love Yourself 結 'Answer'     49.088951
3                    Still With You     47.279051
4                             Proof     47.030681
5                     Bangır Bangır     46.165408
6        Onbir Bir İkibinonbir Veda     35.140709
7                             Önsöz     34.927753
8            Love Yourself 轉 'Tear'     32.227111
9                  Bir Güzellik Yap     28.507920
10                    Bir Bakmışsın     27.418778
11              Beni Durdursan Mı ?     26.085867
12           Sen Nefsine Köle Oldun     25.030400
13                          Gözyaşı     23.126333
14                  BEAUTY IN DEATH     22.863544
15                        Manifesto     22.495502
16            Love Yourself 承 'Her'     22.166046
17                           Yağmur     21.289839
18              MAP OF THE SOUL : 7     19.916642
19                  Dangerous Woman     18.999799

In [ ]:
fig = px.bar(
    album_hours,
    x="hours_played",
    y="master_metadata_album_album_name",
    orientation="h",
    text=album_hours["hours_played"].round(1),
    title="Albums with the Highest Listening Time",
    labels={
        "master_metadata_album_album_name": "Album",
        "hours_played": "Hours Played"
    }
)

fig.update_layout(
    yaxis={"categoryorder": "total ascending"}
)

fig.show()

## 16. Track Analysis

16.1 Most Listened Tracks (Overall)

In [ ]:
top_tracks = (
    spotify
    .dropna(subset=[
        "master_metadata_track_name",
        "master_metadata_album_artist_name"
    ])
    .groupby([
        "master_metadata_track_name",
        "master_metadata_album_artist_name"
    ])
    .agg(
        play_count=("master_metadata_track_name", "count"),
        listening_hours=("hours_played", "sum")
    )
    .sort_values("play_count", ascending=False)
    .head(20)
    .reset_index()
)

top_tracks

,master_metadata_track_name,master_metadata_album_artist_name,play_count,listening_hours
0,Still With You,Jung Kook,861,47.271984
1,3D (feat. Jack Harlow),Jung Kook,599,14.492377
2,Closer to You (feat. Major Lazer),Jung Kook,578,12.151108
3,"One Of The Girls (with JENNIE, Lily Rose Depp)",The Weeknd,550,16.637232
4,double take,Dhruv,548,13.490661
5,Bite Me,ENHYPEN,535,15.024844
6,Attention,Charlie Puth,521,8.924633
7,Run BTS,BTS,519,15.953339
8,Into You,Ariana Grande,516,9.878122
9,Seven (feat. Latto) (Explicit Ver.),Jung Kook,500,7.362992
10,Señorita,Shawn Mendes,487,6.790114
11,Boy With Luv (feat. Halsey),BTS,485,13.340479
12,FAKE LOVE,BTS,485,20.581548
13,Butter,BTS,484,8.308655
14,Walls Could Talk,Halsey,471,4.448661
15,Love Me Again,V,462,7.523355
16,Without Me,Halsey,459,6.999061
17,That That (prod.&feat. SUGA of BTS),PSY,455,8.899446
18,Yes or No,Jung Kook,453,8.591814
19,HEAVEN AND BACK,Chase Atlantic,449,15.460880

In [ ]:
top_tracks["track"] = (
    top_tracks["master_metadata_track_name"]
    + " — "
    + top_tracks["master_metadata_album_artist_name"]
)

fig = px.bar(
    top_tracks,
    x="play_count",
    y="track",
    orientation="h",
    color="listening_hours",
    text="play_count",
    title="Top 20 Most Listened Tracks"
)

fig.update_layout(
    yaxis={"categoryorder": "total ascending"}
)

fig.show()

16.2 Track Preference Comparison

In [ ]:
common_tracks = (
    spotify
    .dropna(subset=["master_metadata_track_name"])
    .groupby([
        "master_metadata_track_name",
        "user"
    ])
    .size()
    .unstack(fill_value=0)
)

common_tracks["Total"] = common_tracks.sum(axis=1)

common_tracks = (
    common_tracks
    .sort_values("Total", ascending=False)
    .head(20)
)

common_tracks

user                                            Eren  Özlem  Total
master_metadata_track_name
Still With You                                     0    862    862
3D (feat. Jack Harlow)                             2    597    599
Closer to You (feat. Major Lazer)                  0    578    578
Friends                                            0    573    573
One Of The Girls (with JENNIE, Lily Rose Depp)     2    548    550
double take                                        0    548    548
Bite Me                                            0    535    535
Attention                                          0    528    528
Run BTS                                            1    518    519
Into You                                           0    518    518
Seven (feat. Latto) (Explicit Ver.)                1    499    500
Señorita                                           0    487    487
Boy With Luv (feat. Halsey)                        0    485    485
FAKE LOVE                                          2    483    485
Butter                                             0    484    484
Walls Could Talk                                   0    471    471
Without Me                                        10    460    470
Love Me Again                                      2    463    465
Dynamite                                           1    456    457
That That (prod.&feat. SUGA of BTS)                0    455    455

## 17. Listening Behavior Analysis

17.1 Skip Rate Analysis

In [ ]:
skip_analysis = (
    spotify
    .groupby("user")
    .agg(
        total_tracks=("skipped", "count"),
        skipped_tracks=("skipped", "sum")
    )
)

skip_analysis["skip_rate (%)"] = (
    skip_analysis["skipped_tracks"] /
    skip_analysis["total_tracks"] * 100
).round(2)

skip_analysis

       total_tracks  skipped_tracks  skip_rate (%)
user
Eren          53518           35608          66.53
Özlem        170909          112587          65.88

In [ ]:
fig = px.bar(
    skip_analysis.reset_index(),
    x="user",
    y="skip_rate (%)",
    color="user",
    text="skip_rate (%)",
    title="Skip Rate by User",
    labels={
        "user": "User",
        "skip_rate (%)": "Skip Rate (%)"
    }
)

fig.show()

17.2 Shuffle Usage

In [ ]:
shuffle_analysis = (
    spotify
    .groupby("user")
    .agg(
        total_tracks=("shuffle", "count"),
        shuffle_used=("shuffle", "sum")
    )
)

shuffle_analysis["shuffle_rate (%)"] = (
    shuffle_analysis["shuffle_used"] /
    shuffle_analysis["total_tracks"] * 100
).round(2)

shuffle_analysis

       total_tracks  shuffle_used  shuffle_rate (%)
user
Eren          53518         29699             55.49
Özlem        170909         81240             47.53

In [ ]:
fig = px.bar(
    shuffle_analysis.reset_index(),
    x="user",
    y="shuffle_rate (%)",
    color="user",
    text="shuffle_rate (%)",
    title="Shuffle Usage Rate",
    labels={
        "user": "User",
        "shuffle_rate (%)": "Shuffle Usage (%)"
    }
)

fig.show()

17.3 Platform Usage Analysis

In [ ]:
platform_usage = (
    spotify
    .groupby(["user", "platform"])
    .size()
    .reset_index(name="play_count")
)

platform_usage

    user                                           platform  play_count
0   Eren                                            android       35530
1   Eren                                                ios       17988
2  Özlem        Android OS 11 API 30 (Xiaomi, Redmi Note 8)          72
3  Özlem          Android OS 7.0 API 24 (samsung, SM-G935F)        3482
4  Özlem  Android OS 8.0.0 API 26 (General Mobile, GM 5 ...           6
5  Özlem                 Windows 10 (10.0.22000; x64; AppX)         852
6  Özlem                 Windows 10 (10.0.22621; x64; AppX)          98
7  Özlem                                            android       71488
8  Özlem                                                ios       77217
9  Özlem                                            windows       17694

In [ ]:
fig = px.bar(
    platform_usage,
    x="platform",
    y="play_count",
    color="user",
    barmode="group",
    title="Platform Usage by User",
    labels={
        "platform": "Platform",
        "play_count": "Play Count",
        "user": "User"
    }
)

fig.show()

In [ ]:
spotify["platform_clean"] = spotify["platform"].str.lower()

spotify["platform_clean"] = (
    spotify["platform_clean"]
    .str.replace(r"android.*", "Android", regex=True)
    .str.replace(r"windows.*", "Windows", regex=True)
    .str.replace(r"web.*", "Web Player", regex=True)
    .str.replace(r"ios.*", "iOS", regex=True)
    .str.replace(r"mac.*", "macOS", regex=True)
)

In [ ]:
platform_usage = (
    spotify
    .groupby(["user", "platform_clean"])
    .size()
    .reset_index(name="play_count")
)

fig = px.bar(
    platform_usage,
    x="platform_clean",
    y="play_count",
    color="user",
    barmode="group",
    title="Platform Usage by User",
    labels={
        "platform_clean": "Platform",
        "play_count": "Play Count"
    }
)

fig.show()

17.4 Offline vs Online Listening

In [ ]:
offline_stats = (
    spotify
    .groupby(["user", "offline"])
    .size()
    .reset_index(name="play_count")
)

offline_stats["offline"] = offline_stats["offline"].map({
    True: "Offline",
    False: "Online"
})

offline_stats

    user  offline  play_count
0   Eren   Online       51875
1   Eren  Offline        1643
2  Özlem   Online      169721
3  Özlem  Offline        1188

In [ ]:
fig = px.bar(
    offline_stats,
    x="user",
    y="play_count",
    color="offline",
    barmode="stack",
    text="play_count",
    title="Offline vs Online Listening",
    labels={
        "user": "User",
        "play_count": "Play Count",
        "offline": "Listening Mode"
    }
)

fig.show()

17.5 Average Listening Duration

In [ ]:
avg_duration = (
    spotify
    .groupby("user")
    .agg(
        average_minutes=("ms_played", lambda x: x.mean() / 60000)
    )
    .round(2)
    .reset_index()
)

avg_duration

    user  average_minutes
0   Eren             1.52
1  Özlem             1.42

In [ ]:
fig = px.bar(
    avg_duration,
    x="user",
    y="average_minutes",
    color="user",
    text="average_minutes",
    title="Average Listening Time per Track",
    labels={
        "user": "User",
        "average_minutes": "Average Minutes"
    }
)

fig.show()

## 18. Spotify Wrapped Summary

18.1 Overall Statistics

In [ ]:
total_hours = spotify["hours_played"].sum()

total_tracks = spotify["master_metadata_track_name"].count()

total_artists = spotify["master_metadata_album_artist_name"].nunique()

total_albums = spotify["master_metadata_album_album_name"].nunique()

first_date = spotify["ts"].min().date()
last_date = spotify["ts"].max().date()

print(f"🎵 Total Tracks Played : {total_tracks:,}")
print(f"🎤 Unique Artists      : {total_artists:,}")
print(f"💿 Unique Albums       : {total_albums:,}")
print(f"⏱️ Total Listening     : {total_hours:,.1f} hours")
print(f"📅 Date Range          : {first_date} → {last_date}")

🎵 Total Tracks Played : 223,099
🎤 Unique Artists      : 3,764
💿 Unique Albums       : 9,001
⏱️ Total Listening     : 5,402.1 hours
📅 Date Range          : 2020-08-18 → 2026-07-23

18.2 User Summary

In [ ]:
user_summary = (
    spotify
    .groupby("user")
    .agg(
        Tracks=("master_metadata_track_name", "count"),
        Artists=("master_metadata_album_artist_name", "nunique"),
        Albums=("master_metadata_album_album_name", "nunique"),
        Hours=("hours_played", "sum")
    )
    .round(1)
)

user_summary

       Tracks  Artists  Albums   Hours
user
Eren    53036     1791    4555  1355.0
Özlem  170063     2661    6016  4047.1

18.3 Top User

In [ ]:
fig = px.bar(
    user_summary.reset_index(),
    x="user",
    y="Hours",
    color="user",
    text="Hours",
    title="Total Listening Hours by User"
)

fig.show()

18.4 Listening Timeline

In [ ]:
timeline = (
    spotify
    .groupby("year")
    .agg(
        Hours=("hours_played", "sum")
    )
    .reset_index()
)

fig = px.line(
    timeline,
    x="year",
    y="Hours",
    markers=True,
    title="Listening Hours Over the Years"
)

fig.show()

18.5 Fun Facts

In [ ]:
print("🎧 Spotify Wrapped Summary")
print("-" * 35)

print(f"Most Active User : {user_summary['Hours'].idxmax()}")
print(f"Total Listening Hours : {spotify['hours_played'].sum():.1f}")
print(f"Unique Artists : {spotify['master_metadata_album_artist_name'].nunique()}")
print(f"Unique Tracks : {spotify['master_metadata_track_name'].nunique()}")
print(f"Listening Period : {spotify['year'].min()} - {spotify['year'].max()}")

🎧 Spotify Wrapped Summary
-----------------------------------
Most Active User : Özlem
Total Listening Hours : 5402.1
Unique Artists : 3764
Unique Tracks : 11780
Listening Period : 2020 - 2026

## 19. Listening Trends

19.1 Monthly Listening Hours

In [ ]:
monthly_hours = (
    spotify
    .groupby(["year", "month"])
    .agg(
        listening_hours=("hours_played", "sum")
    )
    .reset_index()
)

monthly_hours["year_month"] = (
    monthly_hours["year"].astype(str)
    + "-"
    + monthly_hours["month"].astype(str).str.zfill(2)
)

monthly_hours.head()

   year  month  listening_hours year_month
0  2020      8        35.040687    2020-08
1  2020      9         0.076229    2020-09
2  2021     11         0.700417    2021-11
3  2021     12         0.437168    2021-12
4  2022      2         0.071812    2022-02

In [ ]:
fig = px.line(
    monthly_hours,
    x="year_month",
    y="listening_hours",
    markers=True,
    title="Monthly Listening Hours",
    labels={
        "year_month": "Month",
        "listening_hours": "Hours"
    }
)

fig.show()

# Conclusion

This project analyzed Spotify Extended Streaming History data from two users over multiple years.

The analysis explored:
- Listening trends over time
- Favorite artists and tracks
- Listening habits by hour, weekday and month
- User comparisons
- Platform and listening behavior
- Overall listening statistics

The findings demonstrate how data analysis and visualization techniques can transform raw streaming history into meaningful insights about music preferences and listening behavior.

In [ ]:
spotify.to_csv("spotify.csv", index=False)

In [ ]:
from google.colab import files

files.download("spotify.csv")